name: Rolling Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential qt6-base-dev libgl1-mesa-dev

      - name: Build Project
        # بناء المشروع
        run: |
          cmake .
          make

      - name: Update Rolling Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete rolling --cleanup-tag -y || true
          gh release create rolling ./ShamelaOpener --title "Rolling Release" --notes "نسخة محدثة تلقائياً بآخر التعديلات (Rolling)."